### PR TITLE
Improve and cleanup buildsystem

### PR DESCRIPTION
**Pull request by jcfr**

### CODE REVIEW

**Comment by jcfr** [comment]
Note: I still need to test on windows and macos

**Comment by jcfr** [comment]
xref https://github.com/openigtlink/OpenIGTLink/pull/174

**Comment by leochan2009** [comment]
Hi Jean, 
Really appreciate the fix and improvement!
i will have a test on the mac and windows system.

**Comment by leochan2009** [comment]
I test on Mac os, it works fine. Just add one line in the superbuild.cmake file:
Include(ExternalProject)
Try to test on the Windows machine, but my slicer build failed due to QT5.10 issue. 
The issue is related with windows 10 build.
I will report the issue on the Slicer repository.

**Comment by jcfr** [comment]
> Include(ExternalProject)

This is not needed when using the latest Slicer. See [r26984: ENH: Update UseSlicer to conveniently include ExternalProject CMake module](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=26984)

**Comment by jcfr** [comment]
> slicer build failed due to QT5.10 issue.

I am assuming the issue is related to missing WebEngine ? 

If this is the case, make sure to install QWebEngine module. I will have a step by step tutorial for installing Qt 5.10 shortly

**Comment by jcfr** [comment]
Thanks :+1:

**Pull request merged**
