### PR TITLE
ENH: Update to new command classes

### PR DESCRIPTION
**Pull request by Sunderlandkyl**

### CODE REVIEW

**Comment by leochan2009** [comment]
Hi Kyle,

I got the following building error

`
Building CXX object Logic/CMakeFiles/igtlioLogic.dir/igtlioConnector.cxx.o
/Users/longquanchen/Desktop/Slicer/SlicerOpenIGTLink-unixbuild/OpenIGTLinkIO/Logic/igtlioConnector.cxx:836:33: error: no viable conversion from
      'SmartPointer<igtl::RTSCommandMessage>' to 'SmartPointer<igtl::CommandMessage>'
  igtl::CommandMessage::Pointer commandMessage = responseMessage;
`

I think we should do a data type casting in the OpenIGTLinkIO library.
what do you think?

Longquan

**Comment by Sunderlandkyl** [comment]
Yes that makes sense.
Thanks for letting me know, I didn't encounter this with VS14.

**Comment by Sunderlandkyl** [comment]
Should be fixed by https://github.com/IGSIO/OpenIGTLinkIO/pull/55.

**Comment by leochan2009** [comment]
Great, confirmed!

**Pull request merged**
